# Generated by Django 5.0.4 on 2024-05-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answer_options'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bot_response',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='answers.answer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
