# Generated by Django 5.0.4 on 2024-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_bot_response_alter_post_message'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='default_response',
            field=models.ManyToManyField(blank=True, to='questions.qustion'),
        ),
    ]
