# Generated by Django 5.0.4 on 2024-05-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answer_options'),
        ('posts', '0003_post_default_response'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bot_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answers.answer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='default_response',
            field=models.ManyToManyField(blank=True, null=True, to='questions.qustion'),
        ),
    ]
